import type { Theme } from '../types/theme';

export const catppuccinLatte: Theme = {
  metadata: {
    name: 'Catppuccin Latte',
    author: 'Catppuccin',
    variant: 'light',
    version: '1.0',
  },
  palette: {
    black: '#4c4f69',
    red: '#d20f39',
    green: '#40a02b',
    yellow: '#df8e1d',
    blue: '#1e66f5',
    magenta: '#ea76cb',
    cyan: '#179299',
    white: '#5c5f77',
    brightBlack: '#6c6f85',
    brightRed: '#d20f39',
    brightGreen: '#40a02b',
    brightYellow: '#df8e1d',
    brightBlue: '#1e66f5',
    brightMagenta: '#ea76cb',
    brightCyan: '#179299',
    brightWhite: '#5c5f77',
    peach: '#fe640b',
    teal: '#179299',
    mauve: '#8839ef',
    pink: '#ea76cb',
  },
  background: '#eff1f5',
  foreground: '#4c4f69',
  cursor: {
    text: '#eff1f5',
    cursor: '#dc8a78',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 500,
  },
  selection: {
    background: '#ccd0da',
    foreground: '#4c4f69',
  },
  window: {
    opacity: 0.92,
    blurRadius: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ccd0da',
    shadow: true,
    shadowBlur: 24,
    shadowOpacity: 0.15,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: 'JetBrains Mono, Fira Code, monospace',
    fallback: 'monospace',
    size: 14,
    weight: 'normal',
    style: 'normal',
    ligatures: true,
  },
  glass: {
    enabled: true,
    blurRadius: 16,
    noiseOpacity: 0.015,
    saturation: 120,
  },
  animations: {
    enabled: true,
    duration: 200,
    easing: 'ease-out',
  },
  tabBar: {
    height: 36,
    background: '#e6e9ef',
    borderHeight: 1,
    borderColor: '#ccd0da',
    tabPaddingX: 16,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#ccd0da',
    activeBorderColor: '#179299',
    splitterSize: 4,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+PageDown',
    prevTab: 'Ctrl+PageUp',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+ArrowLeft',
    paneRight: 'Ctrl+Shift+ArrowRight',
    paneUp: 'Ctrl+Shift+ArrowUp',
    paneDown: 'Ctrl+Shift+ArrowDown',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+Equal',
    zoomOut: 'Ctrl+Minus',
    zoomReset: 'Ctrl+0',
  },
};
