import type { Theme } from '../types/theme';

export const catppuccinMocha: Theme = {
  metadata: {
    name: 'Catppuccin Mocha',
    author: 'Catppuccin',
    variant: 'dark',
    version: '1.0',
  },
  palette: {
    black: '#1e1e2e',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#cdd6f4',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#f5f9ff',
    peach: '#fab387',
    teal: '#94e2d5',
    mauve: '#cba6f7',
    pink: '#f5c2e7',
  },
  background: '#1e1e2e',
  foreground: '#cdd6f4',
  cursor: {
    text: '#1e1e2e',
    cursor: '#f5e0dc',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 500,
  },
  selection: {
    background: '#313244',
    foreground: '#cdd6f4',
  },
  window: {
    opacity: 0.9,
    blurRadius: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#313244',
    shadow: true,
    shadowBlur: 32,
    shadowOpacity: 0.5,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: 'JetBrains Mono, Fira Code, monospace',
    fallback: 'monospace',
    size: 14,
    weight: 'normal',
    style: 'normal',
    ligatures: true,
  },
  glass: {
    enabled: true,
    blurRadius: 20,
    noiseOpacity: 0.02,
    saturation: 180,
  },
  animations: {
    enabled: true,
    duration: 200,
    easing: 'ease-out',
  },
  tabBar: {
    height: 36,
    background: '#181825',
    borderHeight: 1,
    borderColor: '#313244',
    tabPaddingX: 16,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#313244',
    activeBorderColor: '#94e2d5',
    splitterSize: 4,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+PageDown',
    prevTab: 'Ctrl+PageUp',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+ArrowLeft',
    paneRight: 'Ctrl+Shift+ArrowRight',
    paneUp: 'Ctrl+Shift+ArrowUp',
    paneDown: 'Ctrl+Shift+ArrowDown',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+Equal',
    zoomOut: 'Ctrl+Minus',
    zoomReset: 'Ctrl+0',
  },
};
