import type { Theme } from '../types/theme';

export const ghostty: Theme = {
  metadata: {
    name: 'Ghostty',
    author: 'Pulse',
    variant: 'dark',
    version: '1.0',
  },
  palette: {
    black: '#1a1b26',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#a9b1d6',
    brightBlack: '#414868',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
    peach: '#ff9e64',
    teal: '#7dcfff',
    mauve: '#bb9af7',
    pink: '#ff007c',
  },
  background: '#1a1b26',
  foreground: '#c0caf5',
  cursor: {
    text: '#1a1b26',
    cursor: '#c0caf5',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 600,
  },
  selection: {
    background: '#33467c',
    foreground: '#c0caf5',
  },
  window: {
    opacity: 0.92,
    blurRadius: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1a1b26',
    shadow: true,
    shadowBlur: 24,
    shadowOpacity: 0.4,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: '"JetBrains Mono", "Fira Code", monospace',
    fallback: '"Noto Color Emoji", monospace',
    size: 14,
    weight: 'normal',
    style: 'italic',
    ligatures: true,
    scrollback: 10000,
    fontFeatures: [],
  },
  glass: {
    enabled: true,
    blurRadius: 12,
    noiseOpacity: 0,
    saturation: 150,
  },
  animations: {
    enabled: true,
    duration: 150,
    easing: 'ease-out',
  },
  tabBar: {
    height: 32,
    background: '#16161e',
    borderHeight: 1,
    borderColor: '#292e42',
    tabPaddingX: 12,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#292e42',
    activeBorderColor: '#7aa2f7',
    splitterSize: 2,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+Tab',
    prevTab: 'Ctrl+Shift+Tab',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+H',
    paneRight: 'Ctrl+Shift+L',
    paneUp: 'Ctrl+Shift+K',
    paneDown: 'Ctrl+Shift+J',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+=',
    zoomOut: 'Ctrl+-',
    zoomReset: 'Ctrl+0',
    payloadPalette: '',
    recon: '',
    quickTerminal: 'Ctrl+graveaccent',
  },
  pulse: {
    visualBell: false,
    visualBellDuration: 150,
    commandNotifications: false,
    autoThemeSwitch: false,
    backgroundImageOpacity: 0,
    backgroundImageFit: 'cover',
    scrollbar: false,
    scrollbarStyle: 'overlay',
  },
};
