import type { Theme } from '../types/theme';
import { catppuccinMocha } from './catppuccin-mocha';
import { catppuccinLatte } from './catppuccin-latte';

export { catppuccinMocha } from './catppuccin-mocha';
export { catppuccinLatte } from './catppuccin-latte';

export const dracula: Theme = {
  metadata: {
    name: 'Dracula',
    author: 'Dracula',
    variant: 'dark',
    version: '1.0',
  },
  palette: {
    black: '#282a36',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
    peach: '#ffb86c',
    teal: '#8be9fd',
    mauve: '#bd93f9',
    pink: '#ff79c6',
  },
  background: '#282a36',
  foreground: '#f8f8f2',
  cursor: {
    text: '#282a36',
    cursor: '#f8f8f2',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 500,
  },
  selection: {
    background: '#44475a',
    foreground: '#f8f8f2',
  },
  window: {
    opacity: 0.88,
    blurRadius: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#44475a',
    shadow: true,
    shadowBlur: 32,
    shadowOpacity: 0.4,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: 'JetBrains Mono, Fira Code, monospace',
    fallback: 'monospace',
    size: 14,
    weight: 'normal',
    style: 'normal',
    ligatures: true,
  },
  glass: {
    enabled: true,
    blurRadius: 20,
    noiseOpacity: 0.02,
    saturation: 180,
  },
  animations: {
    enabled: true,
    duration: 200,
    easing: 'ease-out',
  },
  tabBar: {
    height: 36,
    background: '#21222c',
    borderHeight: 1,
    borderColor: '#44475a',
    tabPaddingX: 16,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#44475a',
    activeBorderColor: '#bd93f9',
    splitterSize: 4,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+PageDown',
    prevTab: 'Ctrl+PageUp',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+ArrowLeft',
    paneRight: 'Ctrl+Shift+ArrowRight',
    paneUp: 'Ctrl+Shift+ArrowUp',
    paneDown: 'Ctrl+Shift+ArrowDown',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+Equal',
    zoomOut: 'Ctrl+Minus',
    zoomReset: 'Ctrl+0',
  },
};

export const tokyoNight: Theme = {
  metadata: {
    name: 'Tokyo Night',
    author: 'Enkia',
    variant: 'dark',
    version: '1.0',
  },
  palette: {
    black: '#1a1b26',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#a9b1d6',
    brightBlack: '#414868',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
    peach: '#ff9e64',
    teal: '#7dcfff',
    mauve: '#bb9af7',
    pink: '#ff007c',
  },
  background: '#1a1b26',
  foreground: '#a9b1d6',
  cursor: {
    text: '#1a1b26',
    cursor: '#c0caf5',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 500,
  },
  selection: {
    background: '#33467c',
    foreground: '#a9b1d6',
  },
  window: {
    opacity: 0.87,
    blurRadius: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#33467c',
    shadow: true,
    shadowBlur: 32,
    shadowOpacity: 0.4,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: 'JetBrains Mono, Fira Code, monospace',
    fallback: 'monospace',
    size: 14,
    weight: 'normal',
    style: 'normal',
    ligatures: true,
  },
  glass: {
    enabled: true,
    blurRadius: 20,
    noiseOpacity: 0.02,
    saturation: 180,
  },
  animations: {
    enabled: true,
    duration: 200,
    easing: 'ease-out',
  },
  tabBar: {
    height: 36,
    background: '#16161e',
    borderHeight: 1,
    borderColor: '#33467c',
    tabPaddingX: 16,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#33467c',
    activeBorderColor: '#7aa2f7',
    splitterSize: 4,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+PageDown',
    prevTab: 'Ctrl+PageUp',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+ArrowLeft',
    paneRight: 'Ctrl+Shift+ArrowRight',
    paneUp: 'Ctrl+Shift+ArrowUp',
    paneDown: 'Ctrl+Shift+ArrowDown',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+Equal',
    zoomOut: 'Ctrl+Minus',
    zoomReset: 'Ctrl+0',
  },
};

export const nord: Theme = {
  metadata: {
    name: 'Nord',
    author: 'Arctic Ice Studio',
    variant: 'dark',
    version: '1.0',
  },
  palette: {
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
    peach: '#d08770',
    teal: '#88c0d0',
    mauve: '#b48ead',
    pink: '#b48ead',
  },
  background: '#2e3440',
  foreground: '#d8dee9',
  cursor: {
    text: '#2e3440',
    cursor: '#d8dee9',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 500,
  },
  selection: {
    background: '#434c5e',
    foreground: '#d8dee9',
  },
  window: {
    opacity: 0.88,
    blurRadius: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#434c5e',
    shadow: true,
    shadowBlur: 32,
    shadowOpacity: 0.4,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: 'JetBrains Mono, Fira Code, monospace',
    fallback: 'monospace',
    size: 14,
    weight: 'normal',
    style: 'normal',
    ligatures: true,
  },
  glass: {
    enabled: true,
    blurRadius: 20,
    noiseOpacity: 0.02,
    saturation: 180,
  },
  animations: {
    enabled: true,
    duration: 200,
    easing: 'ease-out',
  },
  tabBar: {
    height: 36,
    background: '#2e3440',
    borderHeight: 1,
    borderColor: '#434c5e',
    tabPaddingX: 16,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#434c5e',
    activeBorderColor: '#88c0d0',
    splitterSize: 4,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+PageDown',
    prevTab: 'Ctrl+PageUp',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+ArrowLeft',
    paneRight: 'Ctrl+Shift+ArrowRight',
    paneUp: 'Ctrl+Shift+ArrowUp',
    paneDown: 'Ctrl+Shift+ArrowDown',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+Equal',
    zoomOut: 'Ctrl+Minus',
    zoomReset: 'Ctrl+0',
  },
};

export const gruvbox: Theme = {
  metadata: {
    name: 'Gruvbox Dark',
    author: 'Gruvbox',
    variant: 'dark',
    version: '1.0',
  },
  palette: {
    black: '#282828',
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    white: '#a89984',
    brightBlack: '#928374',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightMagenta: '#d3869b',
    brightCyan: '#8ec07c',
    brightWhite: '#ebdbb2',
    peach: '#fe8019',
    teal: '#8ec07c',
    mauve: '#d3869b',
    pink: '#d3869b',
  },
  background: '#282828',
  foreground: '#ebdbb2',
  cursor: {
    text: '#282828',
    cursor: '#ebdbb2',
    style: 'block',
    opacity: 1.0,
    blinking: true,
    blinkInterval: 500,
  },
  selection: {
    background: '#3c3836',
    foreground: '#ebdbb2',
  },
  window: {
    opacity: 0.88,
    blurRadius: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3c3836',
    shadow: true,
    shadowBlur: 32,
    shadowOpacity: 0.4,
    paddingX: 0,
    paddingY: 0,
  },
  font: {
    family: 'JetBrains Mono, Fira Code, monospace',
    fallback: 'monospace',
    size: 14,
    weight: 'normal',
    style: 'normal',
    ligatures: true,
  },
  glass: {
    enabled: true,
    blurRadius: 20,
    noiseOpacity: 0.02,
    saturation: 180,
  },
  animations: {
    enabled: true,
    duration: 200,
    easing: 'ease-out',
  },
  tabBar: {
    height: 36,
    background: '#1d2021',
    borderHeight: 1,
    borderColor: '#3c3836',
    tabPaddingX: 16,
  },
  pane: {
    borderWidth: 1,
    borderColor: '#3c3836',
    activeBorderColor: '#fabd2f',
    splitterSize: 4,
  },
  keybindings: {
    newTab: 'Ctrl+Shift+T',
    closeTab: 'Ctrl+Shift+W',
    nextTab: 'Ctrl+PageDown',
    prevTab: 'Ctrl+PageUp',
    splitHorizontal: 'Ctrl+Shift+O',
    splitVertical: 'Ctrl+Shift+E',
    closePane: 'Ctrl+Shift+X',
    paneLeft: 'Ctrl+Shift+ArrowLeft',
    paneRight: 'Ctrl+Shift+ArrowRight',
    paneUp: 'Ctrl+Shift+ArrowUp',
    paneDown: 'Ctrl+Shift+ArrowDown',
    copy: 'Ctrl+Shift+C',
    paste: 'Ctrl+Shift+V',
    search: 'Ctrl+Shift+F',
    commandPalette: 'Ctrl+Shift+P',
    settings: 'Ctrl+Shift+,',
    zoomIn: 'Ctrl+Equal',
    zoomOut: 'Ctrl+Minus',
    zoomReset: 'Ctrl+0',
  },
};

export const builtInThemes: Record<string, Theme> = {
  'catppuccin-mocha': catppuccinMocha,
  'catppuccin-latte': catppuccinLatte,
  'dracula': dracula,
  'tokyo-night': tokyoNight,
  'nord': nord,
  'gruvbox': gruvbox,
};
